name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv      
          source venv/bin/activate 
          pip install --upgrade pip
          pip install flake8 isort black mypy pytest

      - name: Run flake8 linter
        run: |
          source venv/bin/activate
          flake8 src/

      - name: Check isort formatting
        run: |
          source venv/bin/activate
          isort --check-only --diff src/

      - name: Check black formatting
        run: |
          source venv/bin/activate
          black --check -l 79 src/

      - name: Run mypy type checks
        run: |
          source venv/bin/activate
          pip install types-flask types-flask-sqlalchemy types-factory-boy types-faker
          mypy src/

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest src/tests/