name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv      
          source venv/bin/activate 
          pip install --upgrade pip
          pip install flake8 isort black mypy pytest

      - name: Run flake8 linter
        run: |
          source venv/bin/activate
          flake8 fast-API/

      - name: Check isort formatting
        run: |
          source venv/bin/activate
          isort --check-only --diff fast-API/

      - name: Check black formatting
        run: |
          source venv/bin/activate
          black --check -l 79 fast-API/

      - name: Run mypy type checks
        run: |
          source venv/bin/activate
          mypy fast-API/

#      - name: Run tests with pytest
#        run: |
#          source venv/bin/activate
#          pip install -r requirements.txt
#          pytest fast-API//tests/